### ISSUE TITLE
List links in a table using `$page.user.links`

### ISSUE THREAD

**Issue by LeoBorai** [whizzes/quicklink-dashboard#17]
Since https://github.com/whizzes/linx-dashboard/pull/16 capability to list links owned by the session user is possible.

Links must be listed on: `/links` page, where a user will be able to check on its existing links data.

**Comment by Michael-Liendo** [comment]
I can make this feature, you can assign me?

**Comment by LeoBorai** [comment]
> I can make this feature, you can assign me?
> 
> 

Awesome! Of course!
