### ISSUE TITLE
Link creation form

### ISSUE THREAD

**Issue by LeoBorai** [whizzes/quicklink-dashboard#18]
Capability to create links is supported via GraphQL if authenticated.

In order to support link creation from UI a component which holds a form with relevant values is needed.

Currently to create a link we just need:

- URL: The URL where the user must be redirected
- Custom Hash: A custom hash to refer to the link

**Comment by Michael-Liendo** [comment]
I can make this feature. U can assign me?

**Comment by dararod** [comment]
> I can make this feature. U can assign me?
Hi @Michael-Liendo i just asigned you to the issue

**Comment by LeoBorai** [comment]
Resolved on #23
