### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by LeoBorai** [whizzes/quicklink-dashboard#42]
Capability to Login and render usep data.

**Comment by Michael-Liendo** [comment]
This issue is ready in #41

**Comment by LeoBorai** [comment]
> This issue is ready in #41

Hi @Michael-Liendo the goal is to use `exo` for the UI and build most of the project with it. As the project stills on very early development I took the chance of setting it up for you on `main` branch!

**Comment by LeoBorai** [comment]
Thanks @Michael-Liendo !

I was able to test it, still work pending but I think is good as of now.
