### ISSUE TITLE
Provide a design draft

### ISSUE THREAD

**Issue by LeoBorai** [whizzes/quicklink-dashboard#7]
Currently we don't have any design to follow. It would be great to have a design we could build using TailwindCSS.

**Comment by Michael-Liendo** [comment]
I search some design in figma 

1.
![image](https://user-images.githubusercontent.com/70660410/217298387-48faec5c-1d4f-4bb2-988d-6bc516a25ca9.png)
**I like this design for the simplicity, and beautiful **
We can use this design, change the icons, color, and other things. and add the dark mode. 
https://www.figma.com/community/file/1058368833308040012

2.
![image](https://user-images.githubusercontent.com/70660410/217300443-21ceab15-f1cc-44c8-80dd-368c637c6476.png)
Aslo we uso something like this, for the color, and hire.
https://dribbble.com/shots/16753965-Login-Sign-up-Dark-Mode-AW-Universal-Page



Those are the two design that i like, we can combine both for create a new design for the app 😄

**Comment by LeoBorai** [comment]
Thanks for providing these examples @Michael-Liendo! We decided to move on with the [Flowbite Admin Dashboard](https://github.com/themesberg/flowbite-admin-dashboard). A PR with the related progress will be linked to this issue.

**Comment by LeoBorai** [comment]
@Michael-Liendo there's also a Svelte reference here: https://github.com/themesberg/flowbite-svelte-admin-dashboard.

**Comment by Michael-Liendo** [comment]
Oh, sure! The design is very cool.
